export { default as Hero } from './Hero';
export { default as Navbar } from './Navbar';
export { default as Projects } from './Projects';
export { default as TechStack } from './TechStack';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
export { default as Socials } from './Socials';
export { default as WorkExperience } from './WorkExperience';
export { default as OtherProjects } from './OtherProjects';
